/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import Classes.SendGmail;
import Dao.TaiKhoan_Dao;
import Pojo.ThuThu_Pojo;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Asus
 */
public class FrameForgetPassword extends javax.swing.JFrame {

    /**
     * Creates new form FrameLogIn
     */
    public FrameForgetPassword() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        bodyPanel = new javax.swing.JPanel();
        txtTenDN = new javax.swing.JTextField();
        lbUser = new javax.swing.JLabel();
        btNhanLaiMatKhau = new javax.swing.JButton();
        btQuayLaiTrangDN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbLogoForgetPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quên mật khẩu?");
        setResizable(false);

        containerPanel.setBackground(new java.awt.Color(0, 204, 153));

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51), new java.awt.Color(255, 51, 51)), "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 0, 18), new java.awt.Color(255, 51, 51))); // NOI18N

        txtTenDN.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        txtTenDN.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        lbUser.setBackground(new java.awt.Color(255, 255, 255));
        lbUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user.png"))); // NOI18N

        btNhanLaiMatKhau.setBackground(new java.awt.Color(241, 57, 83));
        btNhanLaiMatKhau.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btNhanLaiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btNhanLaiMatKhau.setText("Nhận lại mật khẩu");
        btNhanLaiMatKhau.setBorder(null);
        btNhanLaiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btNhanLaiMatKhauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btNhanLaiMatKhauMouseExited(evt);
            }
        });
        btNhanLaiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhanLaiMatKhauActionPerformed(evt);
            }
        });

        btQuayLaiTrangDN.setBackground(new java.awt.Color(241, 57, 83));
        btQuayLaiTrangDN.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btQuayLaiTrangDN.setForeground(new java.awt.Color(255, 255, 255));
        btQuayLaiTrangDN.setText("Quay lại trang đăng nhập");
        btQuayLaiTrangDN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btQuayLaiTrangDNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btQuayLaiTrangDNMouseExited(evt);
            }
        });
        btQuayLaiTrangDN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuayLaiTrangDNActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bannerForgetPassword.PNG"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Nhập tên tài khoản/tên đăng nhập ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("hệ thống sẽ gửi mật khẩu đến địa chỉ Email của bạn!  ");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(63, 63, 63))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(lbUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btNhanLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btQuayLaiTrangDN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenDN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(btNhanLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btQuayLaiTrangDN)
                .addGap(12, 12, 12))
        );

        txtTenDN.getAccessibleContext().setAccessibleName("");
        txtTenDN.getAccessibleContext().setAccessibleDescription("");

        lbLogoForgetPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/tittleLogin.PNG"))); // NOI18N

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lbLogoForgetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLogoForgetPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bodyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNhanLaiMatKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNhanLaiMatKhauMouseEntered
        // TODO add your handling code here:
        btNhanLaiMatKhau.setBackground(Color.decode("#00CC99"));
    }//GEN-LAST:event_btNhanLaiMatKhauMouseEntered

    private void btNhanLaiMatKhauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btNhanLaiMatKhauMouseExited
        // TODO add your handling code here:
        btNhanLaiMatKhau.setBackground(Color.decode("#F13953"));
    }//GEN-LAST:event_btNhanLaiMatKhauMouseExited

    private void btNhanLaiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhanLaiMatKhauActionPerformed
        // TODO add your handling code here:
        TaiKhoan_Dao tk = new TaiKhoan_Dao();
        ThuThu_Pojo thuThu = tk.layThongTinThuThu(txtTenDN.getText());
        if(thuThu == null){
            JOptionPane.showMessageDialog(getContentPane(), "Tên đăng nhập / tài khoản không đúng!");
            return;
        }
        else
        {
            String content = "Xin chào! " + thuThu.getHoTen() + " mật khẩu quản lý thư viện của bạn là : " + thuThu.getTaiKhoan().getMatKhau();
            SendGmail s = new SendGmail();
            s.sendMail(thuThu.getTaiKhoan().getEmail(),content);
        }
    }//GEN-LAST:event_btNhanLaiMatKhauActionPerformed

    private void btQuayLaiTrangDNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQuayLaiTrangDNMouseExited
        // TODO add your handling code here:
        btQuayLaiTrangDN.setBackground(Color.decode("#F13953"));
    }//GEN-LAST:event_btQuayLaiTrangDNMouseExited

    private void btQuayLaiTrangDNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btQuayLaiTrangDNMouseEntered
        // TODO add your handling code here:
        btQuayLaiTrangDN.setBackground(Color.decode("#00CC99"));
    }//GEN-LAST:event_btQuayLaiTrangDNMouseEntered

    private void btQuayLaiTrangDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuayLaiTrangDNActionPerformed
        // TODO add your handling code here:
        new FrameLogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btQuayLaiTrangDNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameForgetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton btNhanLaiMatKhau;
    private javax.swing.JButton btQuayLaiTrangDN;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbLogoForgetPassword;
    private javax.swing.JLabel lbUser;
    private javax.swing.JTextField txtTenDN;
    // End of variables declaration//GEN-END:variables
}
